FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04

ARG USERNAME=agent
ARG USER_UID=1000
ARG USER_GID=1000

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo ca-certificates curl git openssh-client openssh-server \
    build-essential pkg-config cmake clang libssl-dev gfortran \
    tmux neovim ripgrep fd-find jq less htop \
    python3 python3-dev python3-venv python3-pip python3-setuptools python3-wheel \
    python-is-python3 libffi-dev \
    iputils-ping mtr-tiny iproute2 net-tools dnsutils traceroute netcat-openbsd \
    libopenblas-dev liblapack-dev libmagma-dev \
    vulkan-tools libvulkan1 libegl1 \
  && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid "${USER_GID}" "${USERNAME}" \
  && useradd --uid "${USER_UID}" --gid "${USER_GID}" -m -s /bin/bash "${USERNAME}" \
  && usermod -aG sudo "${USERNAME}" \
  && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/90-${USERNAME}" \
  && chmod 440 "/etc/sudoers.d/90-${USERNAME}"

RUN install -d -m 755 /etc/ssh/sshd_config.d \
  && printf '%s\n' \
    'PermitRootLogin prohibit-password' \
    'PasswordAuthentication no' \
    'KbdInteractiveAuthentication no' \
    'ChallengeResponseAuthentication no' \
    'PubkeyAuthentication yes' \
    > /etc/ssh/sshd_config.d/99-agent-hardening.conf \
  && install -d -m 755 /var/run/sshd

RUN install -d -m 755 /etc/nabled \
  && printf '%s\n' 'nabled_nvidia_image=1' >/etc/nabled/nvidia-image

ENV CARGO_HOME=/home/${USERNAME}/.cargo
ENV RUSTUP_HOME=/home/${USERNAME}/.rustup
ENV HOME=/home/${USERNAME}
ENV PATH=/home/${USERNAME}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV TERM=xterm-256color
ENV COLORTERM=truecolor
ENV PYO3_PYTHON=/usr/bin/python3

USER "${USERNAME}"
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable \
  && rustup component add clippy rustfmt \
  && cargo +stable install just --locked \
  && python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel maturin

RUN printf '%s\n' 'export HOME=/home/'"${USERNAME}" > /home/${USERNAME}/.bash_profile \
  && printf '%s\n' 'export HOME=/home/'"${USERNAME}" > /home/${USERNAME}/.profile \
  && printf '%s\n' 'export HOME=/home/'"${USERNAME}" > /home/${USERNAME}/.bashrc

USER root
RUN install -d -m 1777 /tmp/xdg-runtime \
  && touch /root/.bashrc /root/.bash_profile /root/.bash_logout \
  && touch /root/.no_auto_tmux \
  && chmod a+r /root/.bashrc /root/.bash_profile /root/.bash_logout \
  && printf '%s\n' 'export HOME=/root' >/root/.bash_profile \
  && printf '%s\n' \
    '#!/usr/bin/env bash' \
    'set -eu' \
    'expected_home="$(getent passwd "$(id -u)" | awk -F: "{print \$6}")"' \
    'if [ -n "${expected_home:-}" ] && [ "${HOME:-}" != "${expected_home}" ]; then' \
    '  export HOME="${expected_home}"' \
    'fi' \
    >/etc/profile.d/00-home-from-passwd.sh \
  && chmod 644 /etc/profile.d/00-home-from-passwd.sh

ENV XDG_RUNTIME_DIR=/tmp/xdg-runtime
ENV WGPU_BACKEND=vulkan

WORKDIR /workspace
USER "${USERNAME}"

CMD ["/bin/bash"]
